project:
  type: book

book:
  title: "Toería de Autómatas y Computabilidad Aplicada"
  author: "Cristian Narváez"
  date: "29/09/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - 01-capitulo.qmd
    - 02-capitulo.qmd
    - 03-capitulo.qmd
    - 04-capitulo.qmd
    - 05-capitulo.qmd
    - 06-capitulo.qmd
    - 07-capitulo.qmd
    - participantes.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  epub: default

editor: visual

